//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROS
{
    [Serializable]
    public class TwistMsg : Message
    {
        public const string k_RosMessageName = "ROS_msgs/Twist";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.Vector3Msg linear;
        public Geometry.Vector3Msg angular;

        public TwistMsg()
        {
            this.linear = new Geometry.Vector3Msg();
            this.angular = new Geometry.Vector3Msg();
        }

        public TwistMsg(Geometry.Vector3Msg linear, Geometry.Vector3Msg angular)
        {
            this.linear = linear;
            this.angular = angular;
        }

        public static TwistMsg Deserialize(MessageDeserializer deserializer) => new TwistMsg(deserializer);

        private TwistMsg(MessageDeserializer deserializer)
        {
            this.linear = Geometry.Vector3Msg.Deserialize(deserializer);
            this.angular = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.linear);
            serializer.Write(this.angular);
        }

        public override string ToString()
        {
            return "TwistMsg: " +
            "\nlinear: " + linear.ToString() +
            "\nangular: " + angular.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
